[package]
name = "cpp-meetup"
version = "0.1.0"
authors = ["Beran Martin <martin.beran@avast.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
